### ISSUE TITLE
[bug] Web gorillatoolkit.org down

### ISSUE THREAD

**Issue by 0x111** [gorilla/gorilla.github.io#13]
**Describe the bug**
The website at gorillatoolkit.org is down, due to Go 1.9 being not available anymore for google app engine hosted websites.

**Versions**
not applicable

**Steps to Reproduce**
1. Open https://www.gorillatoolkit.org
2. See error message "Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information."

**Expected behavior**
The website renders and shows the contents of this repo.

**Code Snippets**
no code snippets

**Screenshot**
![Screenshot 2020-08-05 at 22 47 18](https://user-images.githubusercontent.com/34659520/89462597-f29cf080-d76d-11ea-9fd6-5be1b5599b22.png)

**Comment by emmaly** [comment]
I disagree that this should be marked as closed.  The website is still down.  I pay for and manage the gorillatoolkit.org domain name, but I do not manage (nor have access to the App Engine project).  Is there a reason why someone else (@kisielk maybe?) can't take this bug?

**Comment by elithrar** [comment]
Hi @emmaly - there are a couple of other bugs saying the same thing, so I'd closed this one. #11 has the PR that will update the site for GAE.

The issue we have is that only @moraes has owner permissions on the GCP project, and @kisielk is no longer directly involved. I can't fix the problem without access to the project.

My intent is to set up a fresh project this weekend, re-deploy the site, and then reach out to you to point the domain to the new address. Until then, it will remain down.

(I do not have any time until the weekend to fix this)

**Comment by 0x111** [comment]
The mentioned PR is not an issue and was there for more than two years which in between the site was available so this is not directly a duplicate but rather a new issue.

As you also mention further that PR is not resolving the issue since there is nobody to deploy it.

You mention there are a couple others that mention this, where? Here is no issue mentioning the site is down except of this one here.

I understand that the PR could resolve the issue but marking this as a duplicate without being a duplicate is rather a weird practice in my opinion. If I would've created a second PR that could have been a duplicate.

**Comment by elithrar** [comment]
Excuse the curt reply, but I have received 10+ issues and emails in the last 12 hours on this :)

Please refrain from commenting further until we've fixed this, which may take some time.

**Comment by emmaly** [comment]
Are there any open issues on GitHub about the site downtime right now?  https://github.com/gorilla/site/issues says no.  Why not reopen this one?

Until it is fixed, how about I redirect the URL to https://github.com/gorilla/ so people can at least have a shot at getting info, instead of a brick wall?

**Comment by emmaly** [comment]
Domain points to GitHub now.  Let me know when it needs to point elsewhere.

**Comment by emmaly** [comment]
This repo is the correct location for website issues.  Any other issues should be closed.  I believe I've already commented on the two duplicate issues in the project and linked them to this issue.

**Comment by emmaly** [comment]
In case anyone drops by this issue about this, https://pkg.go.dev/search?q=github.com%2Fgorilla is an okay-enough place for documentation for the project while we await the site being brought back up.

**Comment by elithrar** [comment]
Thanks for the help. 

I'm sure you can appreciate that - as the sole remaining maintainer for the Gorilla project - having the site go down and being unable to fix it is pretty frustrating. It was only yesterday that @kisielk named you as the holder of the domain :-) 

I'd like to figure out a way to take ownership of the domain as well, since I'll need to stand up a fresh GCP project. I can then look at sharing ownership with the Go team at Google as an insurance policy against this happening again. The bus factor is pretty high right now.

**Comment by emmaly** [comment]
I still recommend re-opening this issue until it is solved so anyone else that wants to raise an issue can see it's already getting attention.  I am not a developer on the repo, so I am unable to do so myself.

The README for this repo has my name and contact info.  Perhaps not the first place one would look, but it has been there for at least the last 3.5 years.  It's even embedded in the TXT record for gorillatoolkit.org if one had nowhere else to turn and got really desperate.

I would be happy to stand up whatever is necessary for this site to run as intended, including creating the GCP project.  Let me know how I can help.

**Comment by elithrar** [comment]
(this may remain down for some time until I have the bandwidth to resolve this)

**Comment by elithrar** [comment]
@emmaly 

I’ve deployed a working version of the site on GAE in a new GCP project. The site works - although visiting the GAE endpoint directly will 301 you to the `gorillatoolkit.org` site (and then again to github.com/gorilla). 

Options going forward:

1. (easiest) point the domain at the new endpoint. I’d like to confirm that the TLS cert won’t expire on its own / that it auto renews before we do that to avoid other forms of downtime.
2. (Better in long term) I take over the domain, set it up as a custom domain in GAE, and issue a TLS certificate directly within the GCP project where the site runs. 

In order to prevent myself from becoming a single point of failure, I intend to ask a couple of Go team members to co-own the GCP project and domain. You are also welcome to help manage the project if you would like to stay involved.

Let me know your thoughts. I can share the endpoint URL via DM or email.

**Comment by elithrar** [comment]
I’ve also set up CI: Cloud Build will trigger a GAE deployment on any push to master.

**Comment by emmaly** [comment]
Please email me the endpoint and I'll get it set up right away!  I'm at my laptop until about 10pm US Pacific tonight.  We can discuss other options after we get the site back online.

**Comment by emmaly** [comment]
I see that I was added to the project.  I'll grab it out of there.  (I was wrong.  I've emailed you.)

**Comment by elithrar** [comment]
This is now fixed - https://www.gorillatoolkit.org/
